### ISSUE TITLE
Events don't get saved properly

### ISSUE THREAD

**Issue by Nincodedo** [Nincodedo/Ninbot#361]
![image](https://user-images.githubusercontent.com/436953/92330769-125a5980-f037-11ea-9bd3-a1d6dd14f376.png)

**Comment by lokerhp** [comment]
Hey, since this issue is over a year old, is this still a issue?

**Comment by Nincodedo** [comment]
Yeah, it's actually even worse now. Null pointer stops the events from being saved at all.

**Comment by lokerhp** [comment]
Its been some time since I worked on a Discord Bot, but I can try to fix it.

can you assign me?

**Comment by Nincodedo** [comment]
Yeah go for it, I appreciate the help!

**Comment by Nincodedo** [comment]
Hey @lokerhp any progress on this one? If not I'll assign it back to myself.

**Comment by Nincodedo** [comment]
Events were removed so this doesn't matter anymore.
